### ISSUE TITLE
Fabric Version?

### ISSUE THREAD

**Issue by thebrightspark** [hlysine/create_power_loader#4]
Hey, it's a long shot but I thought I'd ask. Is there the possibility that you could get this on to Fabric too? I've got a private modpack on Fabric in 1.20.1 and would love to use this mod.

Am aware that it would mean a bit of a refactor of the project to get it setup for multiple mod loaders, so can understand if it's too much work.

**Comment by hlysine** [comment]
No, I'll not be porting this mod to Fabric, both because I do not know the API, and because there are more important things to do than writing the same mod twice. 

However, I do welcome Fabric forks with proper credits given. I imagine it won't be too difficult for those already developing on Fabric.
